language: go

go:
    - "1.9.4"

env:
  global:
    - GIT_DEPLOY_DIR=public
    - GIT_DEPLOY_BRANCH=gh-pages
    - GIT_DEPLOY_USERNAME="Travis CI"
    - GIT_DEPLOY_EMAIL=hejtmy@gmail.com
    - HUGO_VERSION=0.53

branches:
  only:
    - master # replace by master for Project Pages

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0 # cleanup previous run

script:
  - hugo
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "brainvr.cz" > ${GIT_DEPLOY_DIR}/CNAME; fi'

deploy:
  provider: pages
  skip_cleanup: true
  target-branch: ${GIT_DEPLOY_BRANCH}
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ${GIT_DEPLOY_DIR}
  on:
    branch: master
